apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: vmalert-tenant-2
  namespace: observability
  labels:
    tenant: tenant-2
spec:
  containers:
    - name: config-reloader
      resources:
        limits:
          cpu: 10m
        requests:
          cpu: 10m
  datasource:
    url: http://vmselect-vmcluster.observability.svc.cluster.local:8481/select/2/prometheus
  notifier:
    url: http://vmalertmanager-default-alertmanager.observability.svc:9093
  image: {}
  livenessProbe:
    initialDelaySeconds: 30
  readinessProbe:
    initialDelaySeconds: 30
  resources:
    limits:
      cpu: 30m
      memory: 150Mi
    requests:
      cpu: 10m
      memory: 50Mi
  ruleSelector:
    matchLabels:
      tenant: observability
